development: &default
  adapter: postgresql
  database: copycopter_development
  min_messages: WARNING

test: &test
  <<: *default
  database: copycopter_test

production:
  adapter: postgresql
  database: copycopter_production
